Improved scripts.

diff --git a/src/make-deb b/src/make-deb
--- a/src/make-deb
+++ b/src/make-deb
@@ -71,11 +71,11 @@ echo -e "\x1b[34mUPSTREAM_VERSION:     ${UPSTREAM_VERSION}\x1b[0m"
 echo -e "\x1b[34mPLAIN_VERSION:        ${PLAIN_VERSION}\x1b[0m"
 echo -e "\x1b[34m######################################################################\x1b[0m"
 
-if [ ! -e ./debian.conf ] ; then
-   echo >&2 "ERROR: debian.conf does not exist -> no configuration for the new package!"
+if [ ! -e ./packaging.conf ] ; then
+   echo >&2 "ERROR: packaging.conf does not exist -> no configuration for the new package!"
    exit 1
 fi
-. ./debian.conf
+. ./packaging.conf
 
 
 # ====== Run warp-and-sort tool =============================================
@@ -92,9 +92,9 @@ echo -e ""
 echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating upstream package ======================================\x1b[0m"
 echo -e ""
 if [ "${SKIP_PACKAGE_SIGNING}" != "" -a ${SKIP_PACKAGE_SIGNING} -eq 1 ] ; then
-   ./make-upstream-package ${PACKAGE} ${PACKAGE_VERSION} -skip-signing
+   ./make-upstream-package ${PACKAGE} ${UPSTREAM_VERSION} -skip-signing
 else
-   ./make-upstream-package ${PACKAGE} ${PACKAGE_VERSION} "${MAKE_DIST}"
+   ./make-upstream-package ${PACKAGE} ${UPSTREAM_VERSION} "${MAKE_DIST}"
 fi
 
 for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
diff --git a/src/make-ppa b/src/make-ppa
--- a/src/make-ppa
+++ b/src/make-ppa
@@ -39,13 +39,18 @@ while [ $# -gt 0 ] ; do
    shift
 done
 
+if [ ${DPUT} -eq 0 -a ${COPR} -eq 0 ] ; then
+   COPR=1
+   DPUT=1
+fi
+
 
 # ====== Build source packages ==============================================
 ./clean-deb
 if [ ${DPUT} -ne 0 ] ; then
-   . ./debian.conf
+   . ./packaging.conf
    if [ "${NOT_TARGET_DISTRIBUTIONS}" == "" ] ; then
-      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in debian.conf!"
+      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in packaging.conf!"
       exit 1
    fi
    buildForDistribution=""
@@ -67,7 +72,6 @@ if [ ${DPUT} -ne 0 ] ; then
 fi
 
 if [ ${COPR} -ne 0 ] ; then
-ls -l /home/dreibh/src/hipercontracer/hipercontracer_1.2.2~rc1.2.orig.tar.gz
    if [ -e rpm -o -e ./make-srpm ] ; then
       ./make-srpm || exit 1
    else
