Improved script.

diff --git a/src/make-ppa b/src/make-ppa
--- a/src/make-ppa
+++ b/src/make-ppa
@@ -19,14 +19,20 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
+# These are the supported distributions by Ubuntu Launchpad and Debian Mentors:
+DPUT_DISTRIBUTIONS="
+   trusty
+   $(ubuntu-distro-info --supported)
+   $(ubuntu-distro-info --supported-esm)
+   unstable
+"
+
+
+# ====== Handle arguments ===================================================
 COPR=0
 DPUT=0
-
-# NOTE: These are the supported distributions by Ubuntu Launchpad and Debian:
-DPUT_DISTRIBUTIONS="precise trusty xenial bionic focal jammy noble  oracular  unstable"
-
 while [ $# -gt 0 ] ; do
    if [ "$1" == "dput" ] ; then
       DPUT=1
@@ -42,78 +48,20 @@ while [ $# -gt 0 ] ; do
    shift
 done
 
-if [ ${DPUT} -eq 0 -a ${COPR} -eq 0 ] ; then
+DIRNAME="$(dirname "$0")"
+DPUT_DISTRIBUTIONS="$(echo "${DPUT_DISTRIBUTIONS}" | xargs -n1 | sort -u)"
+if [ ${DPUT} -eq 0 ] && [ ${COPR} -eq 0 ] ; then
    COPR=1
    DPUT=1
 fi
-
 if [ ! -e debian/ ] ; then
    DPUT=0
 fi
 if [ ! -e rpm/ ] ; then
    COPR=0
 fi
-
-
-# ====== Build source packages ==============================================
-./clean-deb
-if [ ${DPUT} -ne 0 ] ; then
-   . ./packaging.conf
-   if [ "${NOT_TARGET_DISTRIBUTIONS}" == "" ] ; then
-      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in packaging.conf!"
-      exit 1
-   fi
-   buildForDistribution=""
-   for dputDistribution in ${DPUT_DISTRIBUTIONS} ; do
-      notATarget=0
-      for notTargetDistribution in ${NOT_TARGET_DISTRIBUTIONS} ; do
-         if [ "${notTargetDistribution}" == "${dputDistribution}" ] ; then
-            notATarget=1
-            break
-         fi
-      done
-      if [ $notATarget -eq 0 ] ; then
-         buildForDistribution="${buildForDistribution} ${dputDistribution}"
-      fi
-   done
-
-   echo "Building for distributions:${buildForDistribution}"
-   ./make-deb ${buildForDistribution}
-fi
-
+COPR_CLI=""
 if [ ${COPR} -ne 0 ] ; then
-   if [ -e rpm -o -e ./make-srpm ] ; then
-      ./make-srpm || exit 1
-   else
-      echo >&2 "ERROR: RPM files not found!"
-      exit 1
-   fi
-fi
-
-
-# ====== dput ===============================================================
-if [ ${DPUT} -ne 0 ] ; then
-   changeFiles=`find . -mindepth 1 -maxdepth 1 -name "*.changes"`
-   for changeFile in ${changeFiles} ; do
-      if [[ ${changeFile} =~ -[0-9]_source.changes$ ]] ; then
-         dput mentors ${changeFile}
-      else
-         dput ppa ${changeFile}
-      fi
-   done
-fi
-
-
-# ====== COPR ===============================================================
-if [ ${COPR} -ne 0 ] ; then
-   PACKAGE=`grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g"`
-   SRPM=`find ${HOME}/rpmbuild/SRPMS -name "${PACKAGE}-*.src.rpm"`
-   if [ ! -e "${SRPM}" ] ; then
-      echo >&2 "ERROR: ${PACKAGE}-*.src.rpm not found!"
-      exit 1
-   fi
-
-   COPR_CLI=""
    for directory in /usr/bin /usr/local/bin ~/.local/bin ; do
       if [ -x "${directory}/copr-cli" ] ; then
          COPR_CLI="${directory}/copr-cli"
@@ -124,7 +72,74 @@ if [ ${COPR} -ne 0 ] ; then
       echo >&2 "ERROR: copr-cli not found!"
       exit 1
    fi
-   echo "Using ${COPR_CLI}"
+fi
 
-   ${COPR_CLI} build --nowait ppa ${SRPM}
+
+# ====== Build Ubuntu/Debian source packages ================================
+if [ ${DPUT} -ne 0 ] ; then
+   . ./packaging.conf
+   if [ "${NOT_TARGET_DISTRIBUTIONS}" == "" ] ; then
+      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in packaging.conf!"
+      exit 1
+   fi
+   buildForDistributions=""
+   for dputDistribution in ${DPUT_DISTRIBUTIONS} ; do
+      notATarget=0
+      for notTargetDistribution in ${NOT_TARGET_DISTRIBUTIONS} ; do
+         if [ "${notTargetDistribution}" == "${dputDistribution}" ] ; then
+            notATarget=1
+            break
+         fi
+      done
+      if [ $notATarget -eq 0 ] ; then
+         if [ "${buildForDistributions}" == "" ] ; then
+            buildForDistributions="${dputDistribution}"
+         else
+            buildForDistributions="${buildForDistributions} ${dputDistribution}"
+         fi
+      fi
+   done
+
+   echo "Building for distributions: ${buildForDistributions}"
+   echo "=> "${DIRNAME}"/build-tool make-source-deb ${buildForDistributions}"
+   "${DIRNAME}"/build-tool make-source-deb ${buildForDistributions}
+fi
+
+
+# ====== Build Fedora source package ========================================
+if [ ${COPR} -ne 0 ] ; then
+   if [ -e rpm ] ; then
+      echo "=> "${DIRNAME}"/build-tool make-source-rpm"
+      "${DIRNAME}"/build-tool make-source-rpm
+   else
+      echo >&2 "ERROR: RPM files not found!"
+      exit 1
+   fi
+fi
+
+
+# # ====== Run dput ===========================================================
+# if [ ${DPUT} -ne 0 ] ; then
+#    changeFiles="$(find . -mindepth 1 -maxdepth 1 -name "*.changes")"
+#    for changeFile in ${changeFiles} ; do
+#       if [[ ${changeFile} =~ -[0-9]_source.changes$ ]] ; then
+#          dput mentors "${changeFile}"
+#       else
+#          dput ppa "${changeFile}"
+#       fi
+#    done
+# fi
+
+
+# ====== Run COPR ===========================================================
+if [ ${COPR} -ne 0 ] ; then
+   PACKAGE="$(grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g")"
+   SRPM="$(find "${HOME}"/rpmbuild/SRPMS -name "${PACKAGE}-*.src.rpm")"
+   if [ ! -e "${SRPM}" ] ; then
+      echo >&2 "ERROR: ${PACKAGE}-*.src.rpm not found!"
+      exit 1
+   fi
+
+   echo "Using ${COPR_CLI}"
+   ${COPR_CLI} build --nowait ppa "${SRPM}"
 fi
