Minor improvement.

diff --git a/src/make-ppa b/src/make-ppa
--- a/src/make-ppa
+++ b/src/make-ppa
@@ -69,6 +69,9 @@ fi
 if [ ${COPR} -ne 0 ] ; then
    if [ -e rpm -o -e ./make-srpm ] ; then
       ./make-srpm || exit 1
+   else
+      echo >&2 "ERROR: RPM files not found!"
+      exit 1
    fi
 fi
 
