Improved script.

diff --git a/src/sort-pkg-plist b/src/sort-pkg-plist
--- a/src/sort-pkg-plist
+++ b/src/sort-pkg-plist
@@ -11,12 +11,12 @@ if [ ! -f "${PKG_PLIST}" ]; then
 fi
 
 while read -r line ; do
-   if [[ "${line}" =~ ^(%%.+%%)([^%]+)$ ]] ; then
+   if [[ "${line}" =~ ^(%%[^/]+%%)(.+)$ ]] ; then
       echo -e "1\t${BASH_REMATCH[1]}\t${BASH_REMATCH[2]}\t${line}"
    elif [[ "${line}" =~ ^([^%]+)$ ]] ; then
       echo -e "0\t\t${BASH_REMATCH[1]}\t${line}"
    else
-      echo >&2 "ERROR: Unexpected input!"
+      echo >&2 "ERROR: Unexpected input ${line}!"
       exit 1
    fi
 done <"${PKG_PLIST}" | \
