Improved script.

diff --git a/src/update-lsm-entry b/src/update-lsm-entry
--- a/src/update-lsm-entry
+++ b/src/update-lsm-entry
@@ -23,65 +23,70 @@
 CHANGELOG_HEADER="`head -n1 debian/changelog`"
 
 # The package name, e.g. MyApplication
-PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
-
+PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`
 # The package distribution, e.g. precise, raring, ...
-PACKAGE_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
+PACKAGE_DISTRIBUTION=`echo ${CHANGELOG_HEADER} | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
 # The package's version, e.g. 1.2.3-1ubuntu1
-PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g"`
+PACKAGE_VERSION=`echo ${CHANGELOG_HEADER} | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g"`
 # The package's output version, e.g. 1.2.3-1ubuntu
-OUTPUT_VERSION=`echo $PACKAGE_VERSION   | sed -e "s/\(ubuntu\|ppa\)[0-9]*$/\1/"`
+OUTPUT_VERSION=`echo ${PACKAGE_VERSION}   | sed -e "s/\(ubuntu\|ppa\)[0-9]*$/\1/"`
 # The package's Debian version, e.g. 1.2.3-1
-DEBIAN_VERSION=`echo $OUTPUT_VERSION    | sed -e "s/\(ubuntu\|ppa\)$//1"`
+DEBIAN_VERSION=`echo ${OUTPUT_VERSION}    | sed -e "s/\(ubuntu\|ppa\)$//1"`
 # The package's upstream version, e.g. 1.2.3
-UPSTREAM_VERSION=`echo $DEBIAN_VERSION  | sed -e "s/-[0-9]*$//"`
+UPSTREAM_VERSION=`echo ${DEBIAN_VERSION}  | sed -e "s/-[0-9]*$//"`
 # The package's plain upstream version, e.g. 1.2.3 (without e.g. ~svn<xxxx>)
-PLAIN_VERSION=`echo $UPSTREAM_VERSION   | sed -e "s/\([0-9\.]*\)[-+~].*$/\1/"`
+PLAIN_VERSION=`echo ${UPSTREAM_VERSION}   | sed -e "s/\([0-9\.]*\)[-+~].*$/\1/"`
 
 
 echo -e "\x1b[34m######################################################################\x1b[0m"
-echo -e "\x1b[34mCHANGELOG_HEADER:     $CHANGELOG_HEADER\x1b[0m"
-echo -e "\x1b[34mPACKAGE:              $PACKAGE\x1b[0m"
-echo -e "\x1b[34mPACKAGE_DISTRIBUTION: $PACKAGE_DISTRIBUTION\x1b[0m"
-echo -e "\x1b[34mPACKAGE_VERSION       $PACKAGE_VERSION\x1b[0m"
-echo -e "\x1b[34mOUTPUT_VERSION:       $OUTPUT_VERSION\x1b[0m"
-echo -e "\x1b[34mDEBIAN_VERSION:       $DEBIAN_VERSION\x1b[0m"
-echo -e "\x1b[34mUPSTREAM_VERSION:     $UPSTREAM_VERSION\x1b[0m"
-echo -e "\x1b[34mPLAIN_VERSION:        $PLAIN_VERSION\x1b[0m"
+echo -e "\x1b[34mCHANGELOG_HEADER:     ${CHANGELOG_HEADER}\x1b[0m"
+echo -e "\x1b[34mPACKAGE:              ${PACKAGE}\x1b[0m"
+echo -e "\x1b[34mPACKAGE_DISTRIBUTION: ${PACKAGE_DISTRIBUTION}\x1b[0m"
+echo -e "\x1b[34mPACKAGE_VERSION       ${PACKAGE_VERSION}\x1b[0m"
+echo -e "\x1b[34mOUTPUT_VERSION:       ${OUTPUT_VERSION}\x1b[0m"
+echo -e "\x1b[34mDEBIAN_VERSION:       ${DEBIAN_VERSION}\x1b[0m"
+echo -e "\x1b[34mUPSTREAM_VERSION:     ${UPSTREAM_VERSION}\x1b[0m"
+echo -e "\x1b[34mPLAIN_VERSION:        ${PLAIN_VERSION}\x1b[0m"
 echo -e "\x1b[34m######################################################################\x1b[0m"
 
 
 # ====== Update LSM entry ===================================================
-LSM_ENTRY="$PACKAGE.lsm"
-if [ ! -e "$LSM_ENTRY" ] ; then
-   echo 2>&1 "ERROR: LSM entry $LSM_ENTRY does not exist!"
+LSM_ENTRY="${PACKAGE}.lsm"
+if [ ! -e "${LSM_ENTRY}" ] ; then
+   echo 2>&1 "ERROR: LSM entry ${LSM_ENTRY} does not exist!"
    exit 1
 fi
-if [ ! -e "$PACKAGE-$UPSTREAM_VERSION.tar.gz" ] ; then
-   echo >&2 "ERROR: File $PACKAGE-$UPSTREAM_VERSION.tar.gz does not exist!"
+for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
+   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-${UPSTREAM_VERSION}.tar.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
+   if [ -e "${UPSTREAM_PACKAGE}" ] ; then
+      break
+   fi
+done
+if [ ! -e "${UPSTREAM_PACKAGE}" ]; then
+   echo >&2 "ERROR: File ${PACKAGE}-${UPSTREAM_VERSION}.tar.* does not exist!"
    exit 1
 fi
 
 today=`env LANG=C date "+%Y-%m-%d"`
-size=`wc -c "$PACKAGE-$UPSTREAM_VERSION.tar.gz" | awk '{ print $1 }'`
+size=`wc -c "${UPSTREAM_PACKAGE}" | awk '{ print $1 }'`
 let size=$size/1024
 
 sed -e "s/^\(Entered-date:[ \t]*\)\(.*\)$/\1$today/g" \
-    -e "s/^\(Version:[ \t]*\)\(.*\)$/\1$UPSTREAM_VERSION/g" \
-    -e "s/\([0-9]*\)\([ ]*kB[ ]*\)\(download\/$PACKAGE-\)\([0-9a-zA-Z\.~+-]*\)\(\.tar\.*\)/$size\2\3$UPSTREAM_VERSION\5/g" \
-   <$LSM_ENTRY >${LSM_ENTRY}.new
+    -e "s/^\(Version:[ \t]*\)\(.*\)$/\1${UPSTREAM_VERSION}/g" \
+    -e "s/\([0-9]*\)\([ ]*kB[ ]*\)\(download\/\)\(${PACKAGE}-\)\([0-9a-zA-Z\.~+-]*\)\(\.tar\.*\).*$/$size\2\3$UPSTREAM_PACKAGE/g" \
+   <${LSM_ENTRY} >${LSM_ENTRY}.new
 
 echo "Update:"
-if colordiff $LSM_ENTRY ${LSM_ENTRY}.new ; then
+if colordiff ${LSM_ENTRY} ${LSM_ENTRY}.new ; then
    echo >&2 "Nothing to update?!"
    exit 1
 fi
-   
+
 
 # ====== Apply changes ======================================================
 echo -en "\x1b[34mRun: Apply update? [yes/no]?\x1b[0m "
 read -er applyChanges
 if [ "$applyChanges" == "yes" -o "$applyChanges" == "y" ] ; then
-   mv $LSM_ENTRY.new ${LSM_ENTRY}
-   thunderbird -compose to=lsm@pug.qqx.org,subject=add,attachment="`pwd`/$LSM_ENTRY" || true &
+   mv ${LSM_ENTRY}.new ${LSM_ENTRY}
+   thunderbird -compose to=lsm@pug.qqx.org,subject=add,attachment="`pwd`/${LSM_ENTRY}" || true &
 fi
