A fix.

diff --git a/src/update-lsm-entry b/src/update-lsm-entry
--- a/src/update-lsm-entry
+++ b/src/update-lsm-entry
@@ -58,7 +58,7 @@ if [ ! -e "$LSM_ENTRY" ] ; then
    exit 1
 fi
 if [ ! -e "$PACKAGE-$UPSTREAM_VERSION.tar.gz" ] ; then
-   echo >&2 "ERROR: File $file does not exist!"
+   echo >&2 "ERROR: File $PACKAGE-$UPSTREAM_VERSION.tar.gz does not exist!"
    exit 1
 fi
 
